### MANAGED BY telegraf ANSIBLE ROLE ###

[global_tags]


# Configuration for telegraf agent
[agent]
    interval = "1s"
    debug = false
    round_interval = true
    flush_interval = "10s"
    flush_jitter = "0s"
    collection_jitter = "0s"
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    quiet = false
    logfile = "C:\\Windows\\Temp\\telegraf.log"
    logfile_rotation_interval = "0"
    logfile_rotation_max_size = "0"
    logfile_rotation_max_archives = 3
    omit_hostname = false

###############################################################################
#                                  OUTPUTS                                    #
###############################################################################

[[outputs.influxdb_v2]]
    urls = ["<<TELEGRAF_URL>>"]
    organization = "<<TELEGRAF_ORGANISATION>>"
    bucket = "Performance"
    token = "<<TELEGRAG_TOKEN>>                                #
###############################################################################

[[inputs.cpu]]
    percpu = true
[[inputs.disk]]
[[inputs.diskio]]
[[inputs.mem]]
# [[inputs.nstat]]
[[inputs.system]]
[[inputs.swap]]
[[inputs.netstat]]
[[inputs.processes]]
[[inputs.kernel]]
[[inputs.win_perf_counters]]
[[inputs.win_perf_counters.object]]
    ObjectName = "Processor Information"
    Instances = ["*"]
    Counters = [ "% Idle Time", "% Interrupt Time", "% Privileged Time", "% User Time", "% Processor Time" ]
    Measurement = "cpu"
    IncludeTotal = true
[[inputs.win_perf_counters.object]]
    ObjectName = "Memory"
    Instances = ["*"]
    Counters = [ "Available Bytes", "Committed Bytes", "Cache Faults/sec", "Demand Zero Faults/sec", "Page Faults/sec", "Pages/sec", "Transition Faults/sec", "Pool Nonpaged Bytes", "Pool Paged Bytes"]
    Measurement = "mem"
[[inputs.win_perf_counters.object]]
    ObjectName = "LogicalDisk"
    Instances = ["*"]
    Counters = [ "% Idle Time", "% Disk Time", "% Disk Read Time", "% Disk Write Time", "% User Time", "% Free Space", "Current Disk Queue Length", "Free Megabytes", "Disk Read Bytes/sec", "Disk Write Bytes/sec", "Disk Reads/sec", "Disk Writes/sec" ]
    Measurement = "disk"
    IncludeTotal = true
[[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [ "Bytes Received/sec", "Bytes Sent/sec", "Packets Received/sec", "Packets Sent/sec" ]
    Measurement = "nic"
[[inputs.win_perf_counters.object]]
    ObjectName = "System"
    Instances = ["------"]
    Counters = [ "Context Switches/sec", "System Calls/sec", "Processor Queue Length", "Threads", "System Up Time", "Processes" ]
    Measurement = "system"
[[inputs.win_perf_counters.object]]
    ObjectName = "Process"
    Instances = ["*"]
    Counters = [ "% Processor Time", "Handle Count", "Private Bytes", "Thread Count", "Virtual Bytes", "Working Set" ]
    Measurement = "process"
    IncludeTotal = true
[[inputs.win_perf_counters.object]]
    ObjectName = "Terminal Services"
    Instances = ["------"]
    Counters = [ "Active Sessions", "Inactive Sessions" ]
    Measurement = "sessions"

###############################################################################
#                                  PROCESSORS                                 #
###############################################################################


###############################################################################
#                                  AGGREGATORS                                #
###############################################################################

