### MANAGED BY telegraf ANSIBLE ROLE ###

[global_tags]


# Configuration for telegraf agent
[agent]
    interval = "1s"
    debug = false
    round_interval = true
    flush_interval = "10s"
    flush_jitter = "0s"
    collection_jitter = "0s"
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    quiet = false
    logfile = "C:\\Windows\\Temp\\telegraf.log"
    logfile_rotation_interval = "0"
    logfile_rotation_max_size = "0"
    logfile_rotation_max_archives = 3
    omit_hostname = false

###############################################################################
#                                  OUTPUTS                                    #
###############################################################################

[[outputs.influxdb_v2]]
    urls = ["<<TELEGRAF_URL>>"]
    organization = "<<TELEGRAF_ORGANISATION>>"
    bucket = "Performance"
    token = "<<TELEGRAG_TOKEN>>    

###############################################################################
#                                  INPUTS                                     #
###############################################################################


[[inputs.vsphere]]
    vcenters =  [ "<<VSPHERE_URL>>" ]
    username = "<<VSPHERE_USERNAME>>"
    password = "<<VSPHERE_PASSWORD>>"
    insecure_skip_verify = true
    timeout = "60s"

###############################################################################
#                                  PROCESSORS                                 #
###############################################################################


###############################################################################
#                                  AGGREGATORS                                #
###############################################################################

